<?php
/**
 * ImranAli
 * Copyright (C) 2020 ImranAli <imibrohi@gmail.com>
 *
 * @package ImranAli_Faq
 * @copyright Copyright (c) 2020 ImranAli
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Imran Ali <imibrohi@gmail.com>
 */
?>
<?php
/** @var $block \ImranAli\Faq\Block\Index\Index */
$faqGroupCollection = $block->getFaqGroupCollection();
$faqCollection = $block->getFaqCollection($block->getGroupId());
$group = $block->getGroupById($block->getGroupId());
?>
<?php if ($block->isShowGroupTitle()) : ?>
    <div class="group-title" id="group<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>">
        <i></i><?php /* @noEscape */ echo $group->getGroupName(); ?>
    </div>
<?php endif; ?>
<div class="faq-accordion">
    <?php $faqCollection = $block->getFaqCollection($group->getId()); ?>
    <?php if ($faqCollection->getSize()) : ?>
        <?php foreach ($faqCollection as $faq) : ?>
            <h3><?php /* @noEscape */ echo $faq->getTitle(); ?></h3>
            <div>
                <p><?php /* @noEscape */ echo $block->filterOutputHtml($faq->getContent()); ?></p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
